repos:
  - repo: local
    hooks:
      - id: asm-check
        name: Check Assembly Files
        entry: bash -c 'for file in $(git diff --cached --name-only --diff-filter=ACMR | grep "\.s$"); do arm-none-eabi-as -o /dev/null "$file" || exit 1; done'
        language: system
        files: \.s$
  - repo: local
    hooks:
      - id: arm-asm-formatter
        name: ARM Assembly Formatter
        entry: ./scripts/format_arm_asm.sh
        language: system
        files: \.(s|S|asm)$
  - repo: local
    hooks:
      - id: arm-asm-elf-file-deleter
        name: ARM Assembly Binary file Deleter
        entry: ./scripts/remove_elf_files.sh
        language: system
        type: [file]
